/* A packrat parser generated by PackCC 1.2.5 */

#ifndef PCC_INCLUDED__LC_H
#define PCC_INCLUDED__LC_H

#include "lambda.h" 
#include "debruijn.h" 

#ifdef __cplusplus
extern "C" {
#endif

typedef struct lc_context_tag lc_context_t;

lc_context_t *lc_create(struct ctx *auxil);
int lc_parse(lc_context_t *ctx, struct lambda **ret);
void lc_destroy(lc_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* PCC_INCLUDED__LC_H */
